# Generated by Django 4.2.16 on 2024-10-22 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("earthquakes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="city",
            unique_together={("name", "latitude", "longitude")},
        ),
        migrations.CreateModel(
            name="CachedEarthquakeData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("data", models.JSONField()),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="earthquakes.city",
                    ),
                ),
            ],
            options={
                "unique_together": {("city", "start_date", "end_date")},
            },
        ),
    ]
